### ISSUE TITLE
Compatibility for Redmine v4.0.x?

### ISSUE THREAD

**Issue by osantos13** [redmineservices/redmine_status_history#3]
Hello,

My company used this plugin heavily, but we lost the functionality when we upgraded to Redmine version 4.0.x. Do you have plans to update the code to make it compatible? Thank you.

**Comment by javiferrer** [comment]
Hello,

Yes, in two weeks will be ready

**Comment by osantos13** [comment]
Great! Glad to hear it and thank you for your effort!

**Comment by osantos13** [comment]
Hello,

ETA on release? Thank you.

**Comment by redmineservices** [comment]
Hello @osantos13 

The plugin is now compatible with redmine 3.x and 4.x. 

BR,
Javier.

**Comment by osantos13** [comment]
Thank you!
