### ISSUE TITLE
Redmine 5.X compatibility?

### ISSUE THREAD

**Issue by gcornacchia** [redmineservices/redmine_status_history#4]
news?

**Comment by formigadiablo** [comment]
Any news on this?

**Comment by vsc55** [comment]
Hi @gcornacchia, @formigadiablo.
I have created a fork and a pr supporting redmine 5.x #5

**Comment by ashrafalzyoud** [comment]
@vsc55 
@gcornacchia 
@formigadiablo 
@giraypultar 
@archonwang 

i note this plugin work only in main project
if the project have sub project
and i cant search status only if im open subproject
i cant search status for all my project in main page

**Comment by ashrafalzyoud** [comment]
i think it be more useful if
1- search in project and subproject
2- added report pdf  for result
3- added time not only date in reports

**Comment by gcornacchia** [comment]
> Hi @gcornacchia, @formigadiablo. I have created a fork and a pr supporting redmine 5.x #5

hi @javiferrer, are you planning to tag and release version 1.0.2 with redmine 5.X compatibility?

**Comment by gcornacchia** [comment]
hi, @javiferrer can you please make a tag (release) of this version?

**Comment by ashrafalzyoud** [comment]
@gcornacchia 
@vsc55 
Can u support in main project and sub project

**Comment by vsc55** [comment]
Hi @ashrafalzyoud,
My Ruby level is not up to this task, so I don't think I'll be able to help much. 😔

**Comment by javiferrer** [comment]
Released 1.0.2.

Gracias @vsc55
